set(_CATKIN_CURRENT_PACKAGE "gps")
set(gps_VERSION "0.0.0")
set(gps_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(gps_PACKAGE_FORMAT "1")
set(gps_BUILD_DEPENDS "actionlib" "move_base_msgs" "roscpp")
set(gps_BUILD_EXPORT_DEPENDS "actionlib" "move_base_msgs" "roscpp")
set(gps_BUILDTOOL_DEPENDS "catkin")
set(gps_BUILDTOOL_EXPORT_DEPENDS )
set(gps_EXEC_DEPENDS "actionlib" "move_base_msgs" "roscpp")
set(gps_RUN_DEPENDS "actionlib" "move_base_msgs" "roscpp")
set(gps_TEST_DEPENDS )
set(gps_DOC_DEPENDS )
set(gps_DEPRECATED "")