#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export LD_LIBRARY_PATH="/home/ubuntu/catkin_ws/devel_isolated/zed_wrapper/lib:/home/ubuntu/catkin_ws/devel_isolated/ublox_gps/lib:/home/ubuntu/catkin_ws/devel_isolated/ublox_msgs/lib:/home/ubuntu/catkin_ws/devel_isolated/ublox_serialization/lib:/home/ubuntu/catkin_ws/devel_isolated/simple_navigation_goals/lib:/home/ubuntu/catkin_ws/devel_isolated/sick_ldmrs_tools/lib:/home/ubuntu/catkin_ws/devel_isolated/sick_ldmrs_driver/lib:/home/ubuntu/catkin_ws/devel_isolated/sick_ldmrs_msgs/lib:/home/ubuntu/catkin_ws/devel_isolated/sick_ldmrs_description/lib:/home/ubuntu/catkin_ws/devel_isolated/rviz_imu_plugin/lib:/home/ubuntu/catkin_ws/devel_isolated/robot_setup_tf/lib:/home/ubuntu/catkin_ws/devel_isolated/phidgets_imu/lib:/home/ubuntu/catkin_ws/devel_isolated/phidgets_ik/lib:/home/ubuntu/catkin_ws/devel_isolated/phidgets_high_speed_encoder/lib:/home/ubuntu/catkin_ws/devel_isolated/phidgets_api/lib:/home/ubuntu/catkin_ws/devel_isolated/line_tracking/lib:/home/ubuntu/catkin_ws/devel_isolated/libphidget21/lib:/home/ubuntu/catkin_ws/devel_isolated/imu_filter_madgwick/lib:/home/ubuntu/catkin_ws/devel_isolated/imu_complementary_filter/lib:/home/ubuntu/catkin_ws/devel_isolated/gps/lib:/home/ubuntu/catkin_ws/devel_isolated/charlie_code/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/aarch64-linux-gnu:/home/ubuntu/catkin_ws/devel_isolated/libsick_ldmrs/lib:/usr/local/cuda/lib:/home/ubuntu/catkin_ws/devel/lib:/usr/local/cuda-8.0/lib64:/home/ubuntu/catkin_ws/install_isolated/lib"
export PATH="/home/ubuntu/catkin_ws/devel_isolated/charlie_code/bin:/opt/ros/kinetic/bin:/home/ubuntu/catkin_ws/devel_isolated/libsick_ldmrs/bin:/usr/local/cuda/bin:/home/ubuntu/catkin_ws/devel/bin:/usr/local/cuda-8.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"